version: '3.8'

services:
  steel-parser:
    build: .
    container_name: parser-steel-app
    ports:
      - "5001:5000"
    volumes:
      # Монтируем папку с базой данных для сохранения данных
      - ./database:/app/database
      # Монтируем папку для логов (если нужно)
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      # Flask порт
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_PORT=5000
    restart: unless-stopped
    networks:
      - parser-steel-network

  telegram-bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    container_name: parsersteel-telegram-bot
    env_file:
      - .env
    environment:
      - PARSERSTEEL_API_URL=http://steel-parser:5000
    restart: unless-stopped
    networks:
      - parser-steel-network
    depends_on:
      - steel-parser

networks:
  parser-steel-network:
    driver: bridge

